export const STS_PRELUDE_MODULE_SPECIFIER = 'sts:prelude';
export const STS_HKT_MODULE_SPECIFIER = 'sts:hkt';
export const STS_TYPECLASSES_MODULE_SPECIFIER = 'sts:typeclasses';
export const STS_RESULT_MODULE_SPECIFIER = 'sts:result';
export const STS_VALUE_MODULE_SPECIFIER = 'sts:value';
export const STS_MATCH_MODULE_SPECIFIER = 'sts:match';
export const STS_FAILURES_MODULE_SPECIFIER = 'sts:failures';
export const STS_URL_MODULE_SPECIFIER = 'sts:url';
export const STS_FETCH_MODULE_SPECIFIER = 'sts:fetch';
export const STS_STREAMS_MODULE_SPECIFIER = 'sts:streams';
export const STS_TEXT_MODULE_SPECIFIER = 'sts:text';
export const STS_RANDOM_MODULE_SPECIFIER = 'sts:random';
export const STS_CRYPTO_MODULE_SPECIFIER = 'sts:crypto';
export const STS_JSON_MODULE_SPECIFIER = 'sts:json';
export const STS_METADATA_MODULE_SPECIFIER = 'sts:metadata';
export const STS_COMPARE_MODULE_SPECIFIER = 'sts:compare';
export const STS_HASH_MODULE_SPECIFIER = 'sts:hash';
export const STS_DERIVE_MODULE_SPECIFIER = 'sts:derive';
export const STS_DECODE_MODULE_SPECIFIER = 'sts:decode';
export const STS_ENCODE_MODULE_SPECIFIER = 'sts:encode';
export const STS_CODEC_MODULE_SPECIFIER = 'sts:codec';
export const STS_CONCURRENCY_MODULE_SPECIFIER = 'sts:concurrency';
export const STS_CONCURRENCY_TASK_MODULE_SPECIFIER = 'sts:concurrency/task';
export const STS_CONCURRENCY_RUNTIME_MODULE_SPECIFIER = 'sts:concurrency/runtime';
export const STS_CONCURRENCY_PARALLEL_MODULE_SPECIFIER = 'sts:concurrency/parallel';
export const STS_CONCURRENCY_SYNC_MODULE_SPECIFIER = 'sts:concurrency/sync';
export const STS_CONCURRENCY_ATOMICS_MODULE_SPECIFIER = 'sts:concurrency/atomics';
export const STS_CAPABILITIES_MODULE_SPECIFIER = 'sts:capabilities';
export const STS_TIME_MODULE_SPECIFIER = 'sts:time';
export const STS_CONSOLE_MODULE_SPECIFIER = 'sts:console';
export const STS_PATH_MODULE_SPECIFIER = 'sts:path';
export const STS_BYTES_MODULE_SPECIFIER = 'sts:bytes';
export const STS_FS_MODULE_SPECIFIER = 'sts:fs';
export const STS_ENV_MODULE_SPECIFIER = 'sts:env';
export const STS_CLI_MODULE_SPECIFIER = 'sts:cli';
export const STS_PROCESS_MODULE_SPECIFIER = 'sts:process';
export const STS_HTTP_MODULE_SPECIFIER = 'sts:http';
export const STS_NET_MODULE_SPECIFIER = 'sts:net';
export const STS_NET_DNS_MODULE_SPECIFIER = 'sts:net/dns';
export const STS_NET_TCP_MODULE_SPECIFIER = 'sts:net/tcp';
export const STS_NET_TLS_MODULE_SPECIFIER = 'sts:net/tls';
export const STS_EXPERIMENTAL_THUNK_MODULE_SPECIFIER = 'sts:experimental/thunk';
export const STS_THUNK_MODULE_SPECIFIER = STS_EXPERIMENTAL_THUNK_MODULE_SPECIFIER;
export const STS_NUMERICS_MODULE_SPECIFIER = 'sts:numerics';
export const STS_MACROS_MODULE_SPECIFIER = 'sts:macros';
export const WEB_DOM_MODULE_SPECIFIER = 'web:dom';
export const EXTERN_GLOBAL_THIS_MODULE_SPECIFIER = 'extern:globalThis';
export const EXTERN_GLOBAL_MODULE_SPECIFIER = 'extern:global';

export const STS_EXPERIMENTAL_SQL_MODULE_SPECIFIER = 'sts:experimental/sql';
export const STS_EXPERIMENTAL_CSS_MODULE_SPECIFIER = 'sts:experimental/css';
export const STS_EXPERIMENTAL_GRAPHQL_MODULE_SPECIFIER = 'sts:experimental/graphql';
export const STS_EXPERIMENTAL_COMPONENT_MODULE_SPECIFIER = 'sts:experimental/component';
export const STS_EXPERIMENTAL_DEBUG_MODULE_SPECIFIER = 'sts:experimental/debug';

export const SOUNDSCRIPT_CORE_MODULE_SPECIFIER = STS_PRELUDE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_HKT_MODULE_SPECIFIER = STS_HKT_MODULE_SPECIFIER;
export const SOUNDSCRIPT_RESULT_MODULE_SPECIFIER = STS_RESULT_MODULE_SPECIFIER;
export const SOUNDSCRIPT_VALUE_MODULE_SPECIFIER = STS_VALUE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_MATCH_MODULE_SPECIFIER = STS_MATCH_MODULE_SPECIFIER;
export const SOUNDSCRIPT_ERRORS_MODULE_SPECIFIER = STS_FAILURES_MODULE_SPECIFIER;
export const SOUNDSCRIPT_URL_MODULE_SPECIFIER = STS_URL_MODULE_SPECIFIER;
export const SOUNDSCRIPT_FETCH_MODULE_SPECIFIER = STS_FETCH_MODULE_SPECIFIER;
export const SOUNDSCRIPT_STREAMS_MODULE_SPECIFIER = STS_STREAMS_MODULE_SPECIFIER;
export const SOUNDSCRIPT_TEXT_MODULE_SPECIFIER = STS_TEXT_MODULE_SPECIFIER;
export const SOUNDSCRIPT_RANDOM_MODULE_SPECIFIER = STS_RANDOM_MODULE_SPECIFIER;
export const SOUNDSCRIPT_CRYPTO_MODULE_SPECIFIER = STS_CRYPTO_MODULE_SPECIFIER;
export const SOUNDSCRIPT_JSON_MODULE_SPECIFIER = STS_JSON_MODULE_SPECIFIER;
export const SOUNDSCRIPT_METADATA_MODULE_SPECIFIER = STS_METADATA_MODULE_SPECIFIER;
export const SOUNDSCRIPT_COMPARE_MODULE_SPECIFIER = STS_COMPARE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_HASH_MODULE_SPECIFIER = STS_HASH_MODULE_SPECIFIER;
export const SOUNDSCRIPT_DERIVE_MODULE_SPECIFIER = STS_DERIVE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_DECODE_MODULE_SPECIFIER = STS_DECODE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_CODEC_MODULE_SPECIFIER = STS_CODEC_MODULE_SPECIFIER;
export const SOUNDSCRIPT_CONCURRENCY_MODULE_SPECIFIER = STS_CONCURRENCY_MODULE_SPECIFIER;
export const SOUNDSCRIPT_CONCURRENCY_TASK_MODULE_SPECIFIER = STS_CONCURRENCY_TASK_MODULE_SPECIFIER;
export const SOUNDSCRIPT_SQL_MODULE_SPECIFIER = STS_EXPERIMENTAL_SQL_MODULE_SPECIFIER;
export const SOUNDSCRIPT_NUMERICS_MODULE_SPECIFIER = STS_NUMERICS_MODULE_SPECIFIER;

export const SOUNDSCRIPT_RUNTIME_PACKAGE_NAME = '@soundscript/soundscript';
export const SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX = '@soundscript/soundscript/experimental';
const BUILTIN_RUNTIME_MODULE_SPECIFIERS = new Map<string, string>([
  [STS_PRELUDE_MODULE_SPECIFIER, SOUNDSCRIPT_RUNTIME_PACKAGE_NAME],
  [STS_HKT_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/hkt`],
  [STS_TYPECLASSES_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/typeclasses`],
  [STS_RESULT_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/result`],
  [STS_VALUE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/value`],
  [STS_MATCH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/match`],
  [STS_FAILURES_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/failures`],
  [STS_URL_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/url`],
  [STS_FETCH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/fetch`],
  [STS_STREAMS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/streams`],
  [STS_TEXT_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/text`],
  [STS_RANDOM_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/random`],
  [STS_CRYPTO_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/crypto`],
  [STS_JSON_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/json`],
  [STS_METADATA_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/metadata`],
  [STS_COMPARE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/compare`],
  [STS_HASH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/hash`],
  [STS_DERIVE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/derive`],
  [STS_DECODE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/decode`],
  [STS_ENCODE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/encode`],
  [STS_CODEC_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/codec`],
  [STS_CONCURRENCY_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/concurrency`],
  [
    STS_CONCURRENCY_TASK_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/concurrency/task`,
  ],
  [
    STS_CONCURRENCY_RUNTIME_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/concurrency/runtime`,
  ],
  [
    STS_CONCURRENCY_PARALLEL_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/concurrency/parallel`,
  ],
  [
    STS_CONCURRENCY_SYNC_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/concurrency/sync`,
  ],
  [
    STS_CONCURRENCY_ATOMICS_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/concurrency/atomics`,
  ],
  [STS_CAPABILITIES_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/capabilities`],
  [STS_TIME_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/time`],
  [STS_CONSOLE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/console`],
  [STS_PATH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/path`],
  [STS_BYTES_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/bytes`],
  [STS_FS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/fs`],
  [STS_ENV_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/env`],
  [STS_CLI_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/cli`],
  [STS_PROCESS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/process`],
  [STS_HTTP_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/http`],
  [STS_NET_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/net`],
  [STS_NET_DNS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/net/dns`],
  [STS_NET_TCP_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/net/tcp`],
  [STS_NET_TLS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/net/tls`],
  [STS_EXPERIMENTAL_THUNK_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/thunk`],
  [STS_NUMERICS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/numerics`],
  [STS_EXPERIMENTAL_SQL_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/sql`],
  [STS_EXPERIMENTAL_CSS_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/css`],
  [
    STS_EXPERIMENTAL_GRAPHQL_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/graphql`,
  ],
  [STS_EXPERIMENTAL_DEBUG_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/debug`],
  [WEB_DOM_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/web/dom`],
]);

export function isSoundscriptProtocolSpecifier(moduleSpecifier: string): boolean {
  return moduleSpecifier.startsWith('sts:');
}

export function isExternModuleSpecifier(moduleSpecifier: string): boolean {
  return moduleSpecifier === EXTERN_GLOBAL_THIS_MODULE_SPECIFIER ||
    moduleSpecifier === EXTERN_GLOBAL_MODULE_SPECIFIER;
}

export function isBuiltinRuntimeModuleSpecifier(moduleSpecifier: string): boolean {
  return BUILTIN_RUNTIME_MODULE_SPECIFIERS.has(moduleSpecifier);
}

export function builtinRuntimeImportSpecifier(
  moduleSpecifier: string,
): string | undefined {
  return BUILTIN_RUNTIME_MODULE_SPECIFIERS.get(moduleSpecifier);
}
