export const STS_PRELUDE_MODULE_SPECIFIER = 'sts:prelude';
export const STS_HKT_MODULE_SPECIFIER = 'sts:hkt';
export const STS_TYPECLASSES_MODULE_SPECIFIER = 'sts:typeclasses';
export const STS_RESULT_MODULE_SPECIFIER = 'sts:result';
export const STS_VALUE_MODULE_SPECIFIER = 'sts:value';
export const STS_MATCH_MODULE_SPECIFIER = 'sts:match';
export const STS_FAILURES_MODULE_SPECIFIER = 'sts:failures';
export const STS_URL_MODULE_SPECIFIER = 'sts:url';
export const STS_FETCH_MODULE_SPECIFIER = 'sts:fetch';
export const STS_TEXT_MODULE_SPECIFIER = 'sts:text';
export const STS_RANDOM_MODULE_SPECIFIER = 'sts:random';
export const STS_JSON_MODULE_SPECIFIER = 'sts:json';
export const STS_METADATA_MODULE_SPECIFIER = 'sts:metadata';
export const STS_COMPARE_MODULE_SPECIFIER = 'sts:compare';
export const STS_HASH_MODULE_SPECIFIER = 'sts:hash';
export const STS_DERIVE_MODULE_SPECIFIER = 'sts:derive';
export const STS_DECODE_MODULE_SPECIFIER = 'sts:decode';
export const STS_ENCODE_MODULE_SPECIFIER = 'sts:encode';
export const STS_CODEC_MODULE_SPECIFIER = 'sts:codec';
export const STS_ASYNC_MODULE_SPECIFIER = 'sts:async';
export const STS_EXPERIMENTAL_THUNK_MODULE_SPECIFIER = 'sts:experimental/thunk';
export const STS_THUNK_MODULE_SPECIFIER = STS_EXPERIMENTAL_THUNK_MODULE_SPECIFIER;
export const STS_NUMERICS_MODULE_SPECIFIER = 'sts:numerics';
export const STS_MACROS_MODULE_SPECIFIER = 'sts:macros';
export const HOST_DOM_MODULE_SPECIFIER = 'host:dom';
export const HOST_NODE_MODULE_SPECIFIER = 'host:node';

export const STS_EXPERIMENTAL_SQL_MODULE_SPECIFIER = 'sts:experimental/sql';
export const STS_EXPERIMENTAL_CSS_MODULE_SPECIFIER = 'sts:experimental/css';
export const STS_EXPERIMENTAL_GRAPHQL_MODULE_SPECIFIER = 'sts:experimental/graphql';
export const STS_EXPERIMENTAL_COMPONENT_MODULE_SPECIFIER = 'sts:experimental/component';
export const STS_EXPERIMENTAL_DEBUG_MODULE_SPECIFIER = 'sts:experimental/debug';

export const SOUNDSCRIPT_CORE_MODULE_SPECIFIER = STS_PRELUDE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_HKT_MODULE_SPECIFIER = STS_HKT_MODULE_SPECIFIER;
export const SOUNDSCRIPT_RESULT_MODULE_SPECIFIER = STS_RESULT_MODULE_SPECIFIER;
export const SOUNDSCRIPT_VALUE_MODULE_SPECIFIER = STS_VALUE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_MATCH_MODULE_SPECIFIER = STS_MATCH_MODULE_SPECIFIER;
export const SOUNDSCRIPT_ERRORS_MODULE_SPECIFIER = STS_FAILURES_MODULE_SPECIFIER;
export const SOUNDSCRIPT_URL_MODULE_SPECIFIER = STS_URL_MODULE_SPECIFIER;
export const SOUNDSCRIPT_FETCH_MODULE_SPECIFIER = STS_FETCH_MODULE_SPECIFIER;
export const SOUNDSCRIPT_TEXT_MODULE_SPECIFIER = STS_TEXT_MODULE_SPECIFIER;
export const SOUNDSCRIPT_RANDOM_MODULE_SPECIFIER = STS_RANDOM_MODULE_SPECIFIER;
export const SOUNDSCRIPT_JSON_MODULE_SPECIFIER = STS_JSON_MODULE_SPECIFIER;
export const SOUNDSCRIPT_METADATA_MODULE_SPECIFIER = STS_METADATA_MODULE_SPECIFIER;
export const SOUNDSCRIPT_COMPARE_MODULE_SPECIFIER = STS_COMPARE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_HASH_MODULE_SPECIFIER = STS_HASH_MODULE_SPECIFIER;
export const SOUNDSCRIPT_DERIVE_MODULE_SPECIFIER = STS_DERIVE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_DECODE_MODULE_SPECIFIER = STS_DECODE_MODULE_SPECIFIER;
export const SOUNDSCRIPT_CODEC_MODULE_SPECIFIER = STS_CODEC_MODULE_SPECIFIER;
export const SOUNDSCRIPT_ASYNC_MODULE_SPECIFIER = STS_ASYNC_MODULE_SPECIFIER;
export const SOUNDSCRIPT_SQL_MODULE_SPECIFIER = STS_EXPERIMENTAL_SQL_MODULE_SPECIFIER;
export const SOUNDSCRIPT_NUMERICS_MODULE_SPECIFIER = STS_NUMERICS_MODULE_SPECIFIER;

export const SOUNDSCRIPT_RUNTIME_PACKAGE_NAME = '@soundscript/soundscript';
export const SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX = '@soundscript/soundscript/experimental';
const BUILTIN_RUNTIME_MODULE_SPECIFIERS = new Map<string, string>([
  [STS_PRELUDE_MODULE_SPECIFIER, SOUNDSCRIPT_RUNTIME_PACKAGE_NAME],
  [STS_HKT_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/hkt`],
  [STS_TYPECLASSES_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/typeclasses`],
  [STS_RESULT_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/result`],
  [STS_VALUE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/value`],
  [STS_MATCH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/match`],
  [STS_FAILURES_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/failures`],
  [STS_URL_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/url`],
  [STS_FETCH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/fetch`],
  [STS_TEXT_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/text`],
  [STS_RANDOM_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/random`],
  [STS_JSON_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/json`],
  [STS_METADATA_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/metadata`],
  [STS_COMPARE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/compare`],
  [STS_HASH_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/hash`],
  [STS_DERIVE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/derive`],
  [STS_DECODE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/decode`],
  [STS_ENCODE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/encode`],
  [STS_CODEC_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/codec`],
  [STS_ASYNC_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/async`],
  [STS_EXPERIMENTAL_THUNK_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/thunk`],
  [STS_NUMERICS_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/numerics`],
  [STS_EXPERIMENTAL_SQL_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/sql`],
  [STS_EXPERIMENTAL_CSS_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/css`],
  [
    STS_EXPERIMENTAL_GRAPHQL_MODULE_SPECIFIER,
    `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/graphql`,
  ],
  [STS_EXPERIMENTAL_DEBUG_MODULE_SPECIFIER, `${SOUNDSCRIPT_EXPERIMENTAL_RUNTIME_PREFIX}/debug`],
  [HOST_DOM_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/host/dom`],
  [HOST_NODE_MODULE_SPECIFIER, `${SOUNDSCRIPT_RUNTIME_PACKAGE_NAME}/host/node`],
]);

export function isSoundscriptProtocolSpecifier(moduleSpecifier: string): boolean {
  return moduleSpecifier.startsWith('sts:');
}

export function isBuiltinRuntimeModuleSpecifier(moduleSpecifier: string): boolean {
  return BUILTIN_RUNTIME_MODULE_SPECIFIERS.has(moduleSpecifier);
}

export function builtinRuntimeImportSpecifier(
  moduleSpecifier: string,
): string | undefined {
  return BUILTIN_RUNTIME_MODULE_SPECIFIERS.get(moduleSpecifier);
}
