export interface GeneratedStdlibMacroFixtureFile {
  readonly path: string;
  readonly contents: string;
}

export function createGeneratedStdlibMacroFixtureFiles(): GeneratedStdlibMacroFixtureFile[] {
  return [
    {
      path: 'package.json',
      contents: JSON.stringify(
        {
          name: 'generated-stdlib-macro-fixture',
          version: '1.0.0',
          type: 'module',
          soundscript: {
            version: 1,
            toolchain: '^0.1.0',
            exports: {
              '.': { source: './src/main.sts' },
            },
          },
        },
        null,
        2,
      ),
    },
    {
      path: 'tsconfig.json',
      contents: JSON.stringify(
        {
          compilerOptions: {
            strict: true,
            noEmit: true,
            target: 'ES2022',
            module: 'ESNext',
            moduleResolution: 'bundler',
          },
          include: ['src/**/*.sts'],
        },
        null,
        2,
      ),
    },
    {
      path: 'src/model.macro.sts',
      contents: [
        "import { macroSignature } from 'sts:macros';",
        '',
        "const DECL_SIGNATURE = macroSignature.of(macroSignature.decl('target'));",
        '',
        '// #[macro(decl)]',
        'export function model() {',
        '  return {',
        "    declarationKinds: ['class'] as const,",
        "    expansionMode: 'augment' as const,",
        '    signature: DECL_SIGNATURE,',
        '    expand(ctx: any) {',
        '      return ctx.output.stmts(ctx.quote.stmts`',
        '        import { codec, decode } from "sts:derive";',
        '        ',
        '        // #[value]',
        '        // #[codec]',
        '        // #[decode.unknownKeys("strict")]',
        '        export class TodoSnapshot {',
        '          readonly id: string;',
        '          readonly title: string;',
        '          constructor(id: string, title: string) {',
        '            this.id = id;',
        '            this.title = title;',
        '          }',
        '        }',
        '      `);',
        '    },',
        '  };',
        '}',
        '',
      ].join('\n'),
    },
    {
      path: 'src/main.sts',
      contents: [
        "import { model } from './model.macro';",
        "import { array as decodeArray } from 'sts:decode';",
        "import { array as encodeArray } from 'sts:encode';",
        "import { decodeJson, encodeJson } from 'sts:json';",
        "import type { Result } from 'sts:result';",
        '',
        '// #[model]',
        'export class Todo {',
        '}',
        '',
        'const strictUnknownKeys = TodoSnapshotCodec.decode({',
        '  id: "todo-1",',
        '  title: "Ship recursive macros",',
        '  extra: true,',
        '});',
        'if (strictUnknownKeys.tag !== "err") {',
        '  throw new Error("expected strict unknown key rejection");',
        '}',
        '',
        'const decoded: Result<readonly TodoSnapshot[], unknown> = decodeJson(',
        '  \'[{"id":"todo-1","title":"Ship recursive macros"}]\',',
        '  decodeArray(TodoSnapshotCodec),',
        ');',
        'if (decoded.tag === "err") {',
        '  throw decoded.error;',
        '}',
        '',
        'const encoded: Result<string, unknown> = encodeJson(',
        '  decoded.value,',
        '  encodeArray(TodoSnapshotCodec),',
        ');',
        'if (encoded.tag === "err") {',
        '  throw encoded.error;',
        '}',
        '',
        'console.log(encoded.value);',
        '',
      ].join('\n'),
    },
  ];
}
