export {
  FAILURES_STDLIB_DECLARATION_FILE as ERROR_STDLIB_DECLARATION_FILE,
  FAILURES_STDLIB_DECLARATION_TEXT as ERROR_STDLIB_DECLARATION_TEXT,
  FAILURES_STDLIB_MODULE_SPECIFIER as ERROR_STDLIB_MODULE_SPECIFIER,
  withStdPackageModuleResolution as withErrorStdlibModuleResolution,
} from './std_package_support.ts';
