import ts from 'typescript';

import {
  EXTERN_GLOBAL_MODULE_SPECIFIER,
  EXTERN_GLOBAL_THIS_MODULE_SPECIFIER,
  isExternModuleSpecifier,
} from '../project/soundscript_runtime_specifiers.ts';

export {
  EXTERN_GLOBAL_MODULE_SPECIFIER,
  EXTERN_GLOBAL_THIS_MODULE_SPECIFIER,
  isExternModuleSpecifier,
};

const EXTERN_DECLARATION_ROOT = '/__soundscript_virtual__/extern';

function hashText(text: string): string {
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

function sanitizeIdentifierPart(text: string): string {
  return text.replace(/[^A-Za-z0-9_$]/gu, '_');
}

function isIdentifierText(text: string): boolean {
  return /^[$A-Z_a-z][$\w]*$/u.test(text);
}

function quotedExportName(name: string): string {
  return isIdentifierText(name) ? name : JSON.stringify(name);
}

function collectNamedImportNames(
  sourceText: string,
  fileName: string,
  moduleSpecifier: string,
): readonly string[] {
  const sourceFile = ts.createSourceFile(
    fileName,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    fileName.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS,
  );
  const names = new Set<string>();

  for (const statement of sourceFile.statements) {
    if (
      !ts.isImportDeclaration(statement) ||
      !ts.isStringLiteralLike(statement.moduleSpecifier) ||
      statement.moduleSpecifier.text !== moduleSpecifier
    ) {
      continue;
    }

    const namedBindings = statement.importClause?.namedBindings;
    if (!namedBindings || !ts.isNamedImports(namedBindings)) {
      continue;
    }

    for (const element of namedBindings.elements) {
      const importedNameNode = element.propertyName ?? element.name;
      if (ts.isIdentifier(importedNameNode) || ts.isStringLiteralLike(importedNameNode)) {
        names.add(importedNameNode.text);
      }
    }
  }

  return [...names].sort((left, right) => left.localeCompare(right));
}

function createExternGlobalThisExport(name: string, index: number): string {
  const localName = `__soundscript_extern_${index}_${sanitizeIdentifierPart(name)}`;
  const propertyName = isIdentifierText(name) ? name : JSON.stringify(name);
  return [
    `declare const ${localName}: __SoundScriptExternGlobalThis extends { readonly ${propertyName}: infer T } ? T : __SoundScriptExternGlobalThis extends { ${propertyName}: infer T } ? T : unknown;`,
    `export { ${localName} as ${quotedExportName(name)} };`,
  ].join('\n');
}

function createExternGlobalExport(name: string, index: number): string {
  const localName = `__soundscript_extern_${index}_${sanitizeIdentifierPart(name)}`;
  const typeReference = isIdentifierText(name) ? `typeof ${name}` : 'unknown';
  return [
    `declare const ${localName}: ${typeReference};`,
    `export { ${localName} as ${quotedExportName(name)} };`,
  ].join('\n');
}

export function createExternDeclarationModuleText(
  moduleSpecifier: string,
  importedNames: readonly string[],
): string {
  const header = [
    '// Generated by Soundscript for reserved extern imports.',
    moduleSpecifier === EXTERN_GLOBAL_THIS_MODULE_SPECIFIER
      ? 'type __SoundScriptExternGlobalThis = typeof globalThis;'
      : '',
  ].filter(Boolean);
  const exports = importedNames.map((name, index) =>
    moduleSpecifier === EXTERN_GLOBAL_THIS_MODULE_SPECIFIER
      ? createExternGlobalThisExport(name, index)
      : createExternGlobalExport(name, index)
  );
  return `${[...header, ...exports].join('\n')}\n`;
}

export function createExternDeclarationModuleFileName(
  moduleSpecifier: string,
  containingFile: string,
  importedNames: readonly string[],
): string {
  const kind = moduleSpecifier === EXTERN_GLOBAL_THIS_MODULE_SPECIFIER ? 'globalThis' : 'global';
  const signature = hashText(`${containingFile}\n${moduleSpecifier}\n${importedNames.join('\n')}`);
  return `${EXTERN_DECLARATION_ROOT}/${kind}/${signature}.d.ts`;
}

export function isExternDeclarationModuleFileName(fileName: string): boolean {
  return fileName.replaceAll('\\', '/').startsWith(`${EXTERN_DECLARATION_ROOT}/`);
}

export function resolveExternDeclarationModule(
  moduleSpecifier: string,
  containingFile: string,
  sourceText: string | undefined,
): { fileName: string; text: string } | undefined {
  if (!isExternModuleSpecifier(moduleSpecifier) || sourceText === undefined) {
    return undefined;
  }

  const importedNames = collectNamedImportNames(sourceText, containingFile, moduleSpecifier);
  const fileName = createExternDeclarationModuleFileName(
    moduleSpecifier,
    containingFile,
    importedNames,
  );
  return {
    fileName,
    text: createExternDeclarationModuleText(moduleSpecifier, importedNames),
  };
}
